# Generated by Django 4.2 on 2024-11-24 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reclammation', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamation',
            options={'ordering': ['-date_reclamation'], 'verbose_name': 'Réclamation', 'verbose_name_plural': 'Réclamations'},
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='trajet',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='lieu',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='matricule_voiture',
            field=models.CharField(default='0000000', max_length=50, verbose_name='Matricule de la Voiture'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='point_arrive',
            field=models.CharField(default='Unknown', max_length=255, verbose_name="Point d'Arrivée"),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='point_depart',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Point de Départ'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='temps',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Temps du Trajet'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_reclamation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de Réclamation'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='etat',
            field=models.CharField(choices=[('en attente', 'En attente'), ('résolue', 'Résolue')], default='en attente', max_length=50, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='sujet',
            field=models.CharField(max_length=255, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
