# Generated by Django 4.2 on 2024-11-25 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclammation', '0003_alter_reclamation_options_remove_reclamation_trajet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='lieu',
        ),
    ]
